apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  namespace: foodorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: monitor:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080

---
apiVersion: v1
kind: Service
metadata:
  name: monitor
  namespace: foodorder
spec:
  selector:
    app: monitor
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

