apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: foodorder
data:
  POSTGRESQL_USER: todo
  POSTGRESQL_PASSWORD: todo
  POSTGRESQL_DATABASE: todos

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-data
  namespace: foodorder
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: foodorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: quay.io/sclorg/postgresql-16-c9s:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/pgsql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-h", "localhost", "-U", "todo", "-d", "todos"]
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 20
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: foodorder
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

