apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: foodorder
data:
  RABBITMQ_DEFAULT_USER: app
  RABBITMQ_DEFAULT_PASS: app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: foodorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: mcr.microsoft.com/azurelinux/base/rabbitmq-server:3
          ports:
            - containerPort: 5672
          envFrom:
            - configMapRef:
                name: rabbitmq-config
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: foodorder
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672

